# Generated by Django 5.1.1 on 2024-10-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_boardsmodel_serialcarroceria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsmodel',
            name='marca',
            field=models.CharField(choices=[('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], default='FORD', max_length=20),
        ),
    ]
