# Generated by Django 5.1.1 on 2024-10-09 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_boardsmodel_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsmodel',
            name='marca',
            field=models.CharField(choices=[('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], default='FORD', max_length=20),
        ),
        migrations.AlterField(
            model_name='boardsmodel',
            name='serialCarroceria',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='boardsmodel',
            name='serialMotor',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
