# Generated by Django 5.1.1 on 2024-10-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_alter_boardsmodel_options_alter_boardsmodel_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardsmodel',
            options={'permissions': (('visualizar_catalogo', 'Can view vehiculo'), ('add_vehiculomodel', 'Can add vehiculo'))},
        ),
        migrations.AlterField(
            model_name='boardsmodel',
            name='serialCarroceria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='boardsmodel',
            name='serialMotor',
            field=models.CharField(max_length=50),
        ),
    ]
